language: node_js
node_js:
  - "6"
before_install:
  - npm i -g npm@5.1.0
install:
  - npm install
script:
  - export DEBUG=*
  - npm -v
  - npm run test
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8